name: Node.js CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-publish:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: npm install
        with:
          args: install
      - name: npm lint
        with:
          args: run lint
      - name: docker build
        with:
          args: build -t thony9799/vaquita .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.USERNAME }}
          DOCKER_USERNAME: ${{ secrets.PASSWORD }}
      - name: docker push
        with:
          args: push thony9799/vaquita
