name: Node.js CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@main
        with:
          args: install
      - name: npm lint
        uses: actions/npm@main
        with:
          args: run lint
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t thony9799/vaquita .
      - name: docker login
        uses: actions/docker/login@main
        env:
          DOCKER_PASSWORD: ${{ secrets.AMBthony1234 }}
          DOCKER_USERNAME: ${{ secrets.thony9799 }}
      - name: docker push
        uses: actions/docker/cli@main
        with:
          args: push thony9799/vaquita
